no_balance_label = "GBP: No Update"
reset_label = "GBP: Reset"

[points]
"Accessibility" = 3
"Admin" = 2
"Atomic" = 2
"Balance" = -5
"Code Improvement" = 2
"Fix" = 3
"Grammar and Formatting" = 1
"Hard Deletes" = 12
"Logging" = 1
"Feature" = -6
"Performance" = 12
"Priority: CRITICAL" = 20
"Priority: High" = 15
"Quality of Life" = 1
"Refactor" = 6
"Sound" = 3
"Sprites" = 3
"Mapping" = -3
"UI" = 3
