[display]
error_level = "hints"

[code_standards]
disallow_relative_type_definitions = true
disallow_relative_proc_definitions = true

[langserver]
dreamchecker = true

[debugger]
engine = "auxtools"

[diagnostics]
var_in_proc_parameter = "error"
redefined_proc = "warning"
